# Generated by Django 4.0 on 2022-01-19 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 15, 17, 36, 368513, tzinfo=utc)),
        ),
    ]
